### ISSUE TITLE
Integrate handling of ceres in g2o

### ISSUE THREAD

**Issue by hemker** [dfki-ric/slam3d#2]
@skasperski 
Recently, g2o introduced a new CMake definition to choose between an os-shipped and a vendored ceres version, namely `G2O_USE_VENDORED_CERES`. I added a patch to the rib.backbone package set to add this definition when building slam3d. Please let me know if you consider to integrate an own handling of this definition or if the patch should remain.

**Comment by skasperski** [comment]
@hemker Have you tried adding libceres-dev as system dependency to slam/g2o instead?

**Comment by hemker** [comment]
Nope, because I was not sure whether the os version fits the slam requirements. Shall I try it?

**Comment by skasperski** [comment]
i can do it as well, just wanted to know whether you already tried it and maybe already know why it is not working.

**Comment by skasperski** [comment]
This should solve the issue when merged:
https://github.com/RainerKuemmerle/g2o/pull/536

**Comment by hemker** [comment]
@skasperski It's merged, so I think this issue can be closed.

**Comment by skasperski** [comment]
Right.
